name: Compile LaTeX CI/CD

on:
  push:
    paths:
      - '**.tex'
      - '**.yml'
      - '**.bib'
      - Makefile
    pull_requests:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/xu-cheng/texlive-full:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile
        run: |
          sudo apt-get install make  
          make

      - name: PDF
        uses: actions/upload-artifact@v3
        with:
          name: pdf-output
          path: '*.pdf'


